import Head from 'next/head'
import Categories from '../../components/Categories'
import Description from '../../components/Description'
import Header from '../../components/Headers/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>ZOMO WEB APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          {/* Navbar */}
            <Header/>
          {/* Header */}
          <Description/>
          {/* Categories */}
          <Categories/>

    </>
  )
}
